name: Create and deploy pages
on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action (Keep workflow alive)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
  create-pages:
    name: Create pages
    runs-on: windows-latest
    env:
      SolutionPath: DataNRO/DataNRO.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore the solution
        run: msbuild $env:SolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        run: nuget restore $env:SolutionPath
      - name: Build the solution
        run: msbuild $env:SolutionPath /t:rebuild /p:Configuration=Release

      - name: Run headless client
        run: |
          cd Output
          .\DataNRO.exe
        env:
          DATA: ${{ secrets.DATA }}

      - name: Move JSON file to Page folder
        run: move Output/Data/* Page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Page

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: create-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4