name: Update data and deploy to GitHub Pages
on:
  schedule:
    - cron: "0 15 * * *"
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      use-sample-data:
        description: "Use sample data"
        type: boolean
        required: false
        default: false
      overwrite-icons:
        description: "ID icons to overwrite, separated by comma, -1 to overwrite all"
        type: string
        required: false
        default: ""
      max-run-seconds:
        description: "Maximum run seconds"
        type: string
        required: false
        default: "3600"
      skip-headless-client:
        description: "Skip headless client"
        type: boolean
        required: false
        default: false
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action (Keep workflow alive)
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v6
        if: github.event_name == 'schedule'
      - uses: liskin/gh-workflow-keepalive@v1
        if: github.event_name == 'schedule'

  # ----------------------------------------------------

  build-headless-client:
    name: Build headless client
    needs: cronjob-based-github-action
    if: github.event.inputs.use-sample-data != 'true'
    runs-on: windows-latest
    env:
      HeadlessClientSolutionPath: HeadlessClient\DataNRO.HeadlessClient.slnx
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup MSBuild
        if: github.event.inputs.skip-headless-client != 'true'
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        if: github.event.inputs.skip-headless-client != 'true'
        uses: NuGet/setup-nuget@v2
      - name: Restore solution
        if: github.event.inputs.skip-headless-client != 'true'
        run: msbuild $env:HeadlessClientSolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        if: github.event.inputs.skip-headless-client != 'true'
        run: nuget restore $env:HeadlessClientSolutionPath
      - name: Build solution
        if: github.event.inputs.skip-headless-client != 'true'
        run: msbuild $env:HeadlessClientSolutionPath /t:rebuild /p:Configuration=Release
      - name: Upload build artifact
        if: github.event.inputs.skip-headless-client != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Output
          path: HeadlessClient/Output/*

  run-headless-client:
    name: Run headless client - ${{ matrix.server.name }}
    needs: build-headless-client
    if: github.event.inputs.use-sample-data != 'true'
    runs-on: windows-latest
    strategy:
      matrix:
        server:
          - {id: 'SV1', name: 'Server 1', secret: 'DATA_SV1'}
          - {id: 'SV2', name: 'Server 2', secret: 'DATA_SV2'}
          - {id: 'SV3', name: 'Server 3', secret: 'DATA_SV3'}
          - {id: 'SV4', name: 'Server 4', secret: 'DATA_SV4'}
          - {id: 'SV5', name: 'Server 5', secret: 'DATA_SV5'}
          - {id: 'SV6', name: 'Server 6', secret: 'DATA_SV6'}
          - {id: 'SV7', name: 'Server 7', secret: 'DATA_SV7'}
          - {id: 'SV8910', name: 'Server 8, 9, 10', secret: 'DATA_SV8910'}
          - {id: 'SV11', name: 'Server 11', secret: 'DATA_SV11'}
          - {id: 'SV12', name: 'Server 12', secret: 'DATA_SV12'}
          - {id: 'SV13', name: 'Server 13', secret: 'DATA_SV13'}
          - {id: 'SV14', name: 'Server 14', secret: 'DATA_SV14'}
          - {id: 'SP1', name: 'Super 1', secret: 'DATA_SP1'}
          - {id: 'SP2', name: 'Super 2', secret: 'DATA_SP2'}
          - {id: 'SP3', name: 'Super 3', secret: 'DATA_SP3'}
          - {id: 'WORLD', name: 'Universe 1', secret: 'DATA_WORLD'}
          - {id: 'INDO', name: 'Indonaga', secret: 'DATA_INDO'}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download build artifact
        if: github.event.inputs.skip-headless-client != 'true'
        uses: dawidd6/action-download-artifact@v19
        with:
          name: Output
          workflow_search: false
          workflow_conclusion: ""
          if_no_artifact_found: fail
          allow_forks: false
          path: Output/
      - name: Download artifact DataNRO-TeaMobi-${{ matrix.server.id }}
        uses: dawidd6/action-download-artifact@v19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: true
          workflow_conclusion: failure
          if_no_artifact_found: warn
          allow_forks: false
          workflow: update-data.yml
          name: DataNRO-TeaMobi-${{ matrix.server.id }}
          # The artifact is a password-protected zip file inside a normal zip file so we need to unpack the outer zip first
          # skip_unpack: true
      - name: Decompress password-protected artifact (TeaMobi) 
        run: |
          if (!(Test-Path -Path Output\Data)) {
            mkdir -Path Output\Data
          }
          if (Test-Path -Path DataNRO-TeaMobi-${{ matrix.server.id }}.zip) {
            7z x DataNRO-TeaMobi-${{ matrix.server.id }}.zip -oOutput\Data\ -p${{ secrets.ZIP_PASSWORD }} -y 
          }
          else {
            7z x SampleData\DataNRO-TeaMobi.zip -oOutput\Data\ -p${{ secrets.ZIP_PASSWORD }} -y 
          }
      - name: Run headless client for ${{ matrix.server.name }}
        if: github.event.inputs.skip-headless-client != 'true'
        run: |
          cd Output
          .\EHVN.DataNRO.HeadlessClient.exe
        env:
          DATA: ${{ secrets[matrix.server.secret] }}
          OVERWRITE_ICONS: ${{ github.event.inputs.overwrite-icons }}
          MAX_RUN_SECONDS: ${{ github.event.inputs.max-run-seconds }}
      - name: Create password-protected zip file (${{ matrix.server.name }})
        run: |
          cd Output\Data
          7z a -p${{ secrets.ZIP_PASSWORD }} -mx=5 -y ..\..\DataNRO-TeaMobi-${{ matrix.server.id }}.zip .\
      - name: Upload password-protected artifact ${{ matrix.server.name }}
        uses: actions/upload-artifact@v4
        with:
          name: DataNRO-TeaMobi-${{ matrix.server.id }}
          path: DataNRO-TeaMobi-${{ matrix.server.id }}.zip

  build-and-deploy-pages:
    name: Build and deploy pages
    needs: run-headless-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download artifact DataNRO-TeaMobi-*
        uses: dawidd6/action-download-artifact@v19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: DataNRO-TeaMobi-.*
          workflow_search: false
          workflow_conclusion: ""
          if_no_artifact_found: fail
          allow_forks: false
          name_is_regexp: true
          path: .\
          # The artifact is a password-protected zip file inside a normal zip file so we need to unpack the outer zip first
          # skip_unpack: true
      - run: tree -d
      - run: tree -a
      - name: Decompress password-protected artifacts (TeaMobi)
        run: |
          for file in DataNRO-TeaMobi-*.zip; do
            7z x "$file" -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          done
      - name: Decompress password-protected sample data (private servers)
        run: |
          7z x SampleData/DataNRO-HSNR.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-BlueFake.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-ILoveNRO.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Build page
        run: |
          cd Page
          npm install
          npm run build
      - run: tree -d
      - name: Copy index.html (Dirty trick)
        run: |
          cp Page/dist/index.html Page/dist/TeaMobi/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server TeaMobi/g' Page/dist/TeaMobi/index.html
          cp Page/dist/index.html Page/dist/HSNR/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server HSNR/g' Page/dist/HSNR/index.html
          cp Page/dist/index.html Page/dist/BlueFake/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server NRO Blue/g' Page/dist/BlueFake/index.html
          cp Page/dist/index.html Page/dist/ILoveNRO/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server Tôi yêu Ngọc Rồng/g' Page/dist/ILoveNRO/index.html
          cp Page/dist/index.html Page/dist/404.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Not found/g' Page/dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: Page/dist
      # - name: Configure GitHub Pages
      #   uses: actions/configure-pages@v5
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
      # - name: Delete page artifact
      #   uses: geekyeggo/delete-artifact@v6
      #   with:
      #     name: github-pages
      - name: Delete output artifact
        uses: geekyeggo/delete-artifact@v6
        with:
          name: Output

  # ----------------------------------------------------

  update-using-sample-data:
    name: Update data and deploy using sample data
    needs: cronjob-based-github-action
    if: github.event.inputs.use-sample-data == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Decompress password-protected sample data (TeaMobi)
        run: 7z x SampleData/DataNRO-TeaMobi.zip -oOutput/Data/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Upload password-protected artifact DataNRO-TeaMobi
        uses: actions/upload-artifact@v4
        with:
          name: DataNRO-TeaMobi
          path: SampleData/DataNRO-TeaMobi.zip
      - name: Decompress password-protected sample data (Private servers)
        run: |
          7z x SampleData/DataNRO-HSNR.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-BlueFake.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-ILoveNRO.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Move sample data to Page (TeaMobi)
        run: mv -f Output/Data/TeaMobi Page/public/
      - name: Build page
        run: |
          cd Page
          npm install
          npm run build
      - name: Copy index.html (Dirty trick)
        run: |
          cp Page/dist/index.html Page/dist/TeaMobi/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server TeaMobi/g' Page/dist/TeaMobi/index.html
          cp Page/dist/index.html Page/dist/HSNR/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server HSNR/g' Page/dist/HSNR/index.html
          cp Page/dist/index.html Page/dist/BlueFake/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server NRO Blue/g' Page/dist/BlueFake/index.html
          cp Page/dist/index.html Page/dist/ILoveNRO/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server Tôi yêu Ngọc Rồng/g' Page/dist/ILoveNRO/index.html
          cp Page/dist/index.html Page/dist/404.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Not found/g' Page/dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: Page/dist
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4    
      - name: Delete page artifact
        uses: geekyeggo/delete-artifact@v6
        with:
          name: github-pages