name: Update data and deploy to GitHub Pages
on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
    - 'DataNRO/**'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action (Keep workflow alive)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2

  update-data:
    name: Update data
    runs-on: windows-latest
    env:
      SolutionPath: DataNRO/DataNRO.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore the solution
        run: msbuild $env:SolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        run: nuget restore $env:SolutionPath
      - name: Build the solution
        run: msbuild $env:SolutionPath /t:rebuild /p:Configuration=Release
      - name: Run headless client
        run: |
          cd Output
          .\DataNRO.exe
        env:
          DATA: ${{ secrets.DATA }}
          PROXY: ${{ secrets.PROXY }}
      - name: Download artifact DataNRO
        uses: dawidd6/action-download-artifact@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: true
          workflow_conclusion: success
          if_no_artifact_found: fail
          allow_forks: false
          workflow: update-data.yml
          name: DataNRO
          path: Page
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataNRO
          path: Output\Data
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Copy JSON file to Page folder
        run: Copy-Item -Path Output/Data/* -Destination Page -Recurse -Force
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Page

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-data
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4