name: Update data and deploy to GitHub Pages
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      use-sample-data:
        description: "Use sample data"
        type: boolean
        required: false
        default: false
      overwrite-icons:
        description: "ID icons to overwrite, separated by comma, -1 to overwrite all"
        type: string
        required: false
        default: ""
      max-run-seconds:
        description: "Maximum run seconds"
        type: string
        required: false
        default: "4500"
      force-proxy:
        description: "Force using proxy"
        type: boolean
        required: false
        default: false
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action (Keep workflow alive)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'schedule'
      - uses: liskin/gh-workflow-keepalive@v1
        if: github.event_name == 'schedule'

  # ----------------------------------------------------

  update-data-TeaMobi:
    name: Update data (TeaMobi)
    needs: cronjob-based-github-action
    if: github.event.inputs.use-sample-data != 'true'
    runs-on: windows-latest
    env:
      CLISolutionPath: CLI\DataNRO.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore DataNRO
        run: msbuild $env:CLISolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        run: nuget restore $env:CLISolutionPath
      - name: Build DataNRO.CLI
        run: msbuild $env:CLISolutionPath /t:rebuild /p:Configuration=Release
      - name: Download artifact DataNRO-TeaMobi
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: true
          workflow_conclusion: success
          if_no_artifact_found: warn
          allow_forks: false
          workflow: update-data.yml
          name: DataNRO-TeaMobi
          skip_unpack: true
          path: Output
      - name: Decompress password-protected artifact (TeaMobi)
        run: |
          if (Test-Path -Path Output\DataNRO-TeaMobi.zip) {
            7z x DataNRO-TeaMobi.zip -oOutput\ -p${{ secrets.ZIP_PASSWORD }} -y 
          }
          else {
            7z x SampleData\DataNRO-TeaMobi.zip -oOutput\Data\ -p${{ secrets.ZIP_PASSWORD }} -y 
          }
      - name: Run headless client
        run: |
          cd Output
          .\DataNRO.CLI.exe
        env:
          DATA: ${{ secrets.DATA_TEAMOBI }}
          PROXY: ${{ secrets.PROXY }}
          OVERWRITE_ICONS: ${{ github.event.inputs.overwrite-icons }}
          MAX_RUN_SECONDS: ${{ github.event.inputs.max-run-seconds }}
          FORCE_PROXY:  ${{ github.event.inputs.force-proxy }}
      - name: Create password-protected zip file (TeaMobi)
        run: 7z a -p${{ secrets.ZIP_PASSWORD }} -mx=5 -y Output\DataNRO-TeaMobi.zip Output\Data\*.*
      - run: tree /f Output
      - name: Upload password-protected artifact DataNRO-TeaMobi
        uses: actions/upload-artifact@v4
        with:
          name: DataNRO-TeaMobi
          path: Output/DataNRO-TeaMobi.zip

  build-and-deploy-pages:
    name: Build and deploy pages
    needs: update-data-TeaMobi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact DataNRO-TeaMobi
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: DataNRO-TeaMobi
          workflow_search: false
          workflow_conclusion: ""
          if_no_artifact_found: fail
          allow_forks: false
          path: Page/public
      - name: Decompress password-protected sample data (private servers)
        run: |
          7z x SampleData/DataNRO-HSNR.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-BlueFake.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-ILoveNRO.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Build page
        run: |
          cd Page
          npm install
          npm run build
      - name: Copy index.html (Dirty trick)
        run: |
          cp Page/dist/index.html Page/dist/TeaMobi/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server TeaMobi/g' Page/dist/TeaMobi/index.html
          cp Page/dist/index.html Page/dist/HSNR/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server HSNR/g' Page/dist/HSNR/index.html
          cp Page/dist/index.html Page/dist/BlueFake/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server NRO Blue/g' Page/dist/BlueFake/index.html
          cp Page/dist/index.html Page/dist/ILoveNRO/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server Tôi yêu Ngọc Rồng/g' Page/dist/ILoveNRO/index.html
          cp Page/dist/index.html Page/dist/404.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Not found/g' Page/dist/404.html
      # - name: Deploy pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: Page/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Page/dist
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete page artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages

  # ----------------------------------------------------

  update-data-sample:
    name: Update data and deploy using sample data
    needs: cronjob-based-github-action
    if: github.event.inputs.use-sample-data == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Decompress password-protected sample data (TeaMobi)
        run: 7z x SampleData/DataNRO-TeaMobi.zip -oOutput/Data/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Upload artifact DataNRO-TeaMobi
        uses: actions/upload-artifact@v4
        with:
          name: DataNRO-TeaMobi
          path: Output/Data
      - name: Decompress password-protected sample data (Private servers)
        run: |
          7z x SampleData/DataNRO-HSNR.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-BlueFake.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
          7z x SampleData/DataNRO-ILoveNRO.zip -oPage/public/ -p${{ secrets.ZIP_PASSWORD }} -y
      - name: Move sample data to Page (TeaMobi)
        run: mv -f Output/Data/TeaMobi Page/public/
      - name: Build page
        run: |
          cd Page
          npm install
          npm run build
      - name: Copy index.html (Dirty trick)
        run: |
          cp Page/dist/index.html Page/dist/TeaMobi/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server TeaMobi/g' Page/dist/TeaMobi/index.html
          cp Page/dist/index.html Page/dist/HSNR/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server HSNR/g' Page/dist/HSNR/index.html
          cp Page/dist/index.html Page/dist/BlueFake/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server NRO Blue/g' Page/dist/BlueFake/index.html
          cp Page/dist/index.html Page/dist/ILoveNRO/index.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Server Tôi yêu Ngọc Rồng/g' Page/dist/ILoveNRO/index.html
          cp Page/dist/index.html Page/dist/404.html
          sed -i 's/DataNRO by ElectroHeavenVN/DataNRO - Not found/g' Page/dist/404.html
      # - name: Deploy pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: Page/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Page/dist
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4    
      - name: Delete page artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages